In [2]:
!pip install numpy


In [3]:
import numpy as np

#create array using numpy
## create 1D array
arr1=np.array([1,2,3,4])
print(arr1)
print(type(arr1)) #n-D array
print(arr1.shape) # (4,)means 1-D array

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [4]:
#Reshaping the 1D array
arr2= np.array([1,3,5,7])
print(arr2.reshape(1,4)) #means 1 row and 4 columns
print(type(arr2))

[[1 3 5 7]]
<class 'numpy.ndarray'>


In [5]:
# 1D array
arr2=np.array([1,3,5,7,9])
arr2.shape

(5,)

In [6]:
# 2D array
arr3= np.array([[1,2,3,4],[5,6,8,9]])
print(arr3)
print(arr3.shape)

[[1 2 3 4]
 [5 6 8 9]]
(2, 4)


In [33]:
# arrange() function
np.arange(0,10,2).reshape(5,1) #0-> start, 10->till(excluded), 2--> steps

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
# ones() inbuild function
#2D Array
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
#1D array
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
#eye() inbuilt function
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [11]:
#eye() inbuilt function
np.eye(3, 4,k=2, dtype=int)

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [12]:
# Attributes of Numpy Array
arr= np.array([[1,2,3],[4,5,6]])
print("Array\n", arr)
print("Shape: ", arr.shape)
print("Number of Dimension: ", arr.ndim)
print("Size (number of elements): ", arr.size)
print("data type: ", arr.dtype)
print("Item size (int bytes): ", arr.itemsize)


Array
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of Dimension:  2
Size (number of elements):  6
data type:  int64
Item size (int bytes):  8


In [13]:
# Numpy Vectorized Opertions
arr1= np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Element wise Addition
print("Addition: ", arr1 + arr2)

## Element wise Substration
print("Substration: ", arr2-arr1)

# Element wise Multiplication
print("Multiplication: ", arr1 * arr2)

# Element wise Division
print("Division: ", arr2/arr1)

# Element wise Modulus
print("Remainder: ", arr2 % arr1)

Addition:  [11 22 33 44 55]
Substration:  [ 9 18 27 36 45]
Multiplication:  [ 10  40  90 160 250]
Division:  [10. 10. 10. 10. 10.]
Remainder:  [0 0 0 0 0]


In [14]:
# Universal function
arr= np.array([2,4,8,25])

# sqaure root
print(np.sqrt(arr))

# Exponential 
print(np.exp(arr))

# Sin 
print(np.sin(arr))

#cos
print(np.cos(arr))



[1.41421356 2.         2.82842712 5.        ]
[7.38905610e+00 5.45981500e+01 2.98095799e+03 7.20048993e+10]
[ 0.90929743 -0.7568025   0.98935825 -0.13235175]
[-0.41614684 -0.65364362 -0.14550003  0.99120281]


In [15]:
#array slicing and indexing
arr= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
# Access 1st element
print(arr[0][0])

1


In [17]:
# Access 7 , 8 and 11 , 12
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [18]:
# Access 3,4,7,8
arr[0:2:,2:]

array([[3, 4],
       [7, 8]])

In [19]:
#Access 6,7,10,11
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [20]:
# Modify array element
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [21]:
arr[1:2]=12
print(arr)

[[100   2   3   4]
 [ 12  12  12  12]
 [  9  10  11  12]]


In [ ]:
# Statistical concept--> Normalization
# To have mean of 0 and standard deviation of 1

data= np.array([1,2,3,4,5])

# Calculate the mean and standard deviation

mean = np.mean(data)
std_dev= np.std(data)

#Normalize data

normalized_data= (data- mean)/std_dev
print("Normalized data: ", normalized_data)



Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [27]:
data= np.array([1,2,3,4,5,6,7,8,9])

#Mean
mean =np.mean(data)
print("Mean: ", mean)

#Mediam
median = np.median(data)
print("Median: ", median)

#Standard Deviation
std_dev= np.std(data)
print("Standard Deviation: ", std_dev)

#Variance
variance= np.var(data)
print("Variance: ", variance)


Mean:  5.0
Median:  5.0
Standard Deviation:  2.581988897471611
Variance:  6.666666666666667


In [32]:
#Logical Operation
data= np.array([1,2,3,4,5,6,7,8,9,19])

print(data[data<5])
print(data[(data >=7) & (data <9)])

[1 2 3 4]
[7 8]
